#!/usr/bin/env bash

PRIVATE_KEY_FILE="../../../Cloud.pem"
EBAY="ubuntu@54.242.23.131"
AMAZON="ubuntu@54.224.84.191"
WALMART="ubuntu@23.22.194.103"
BESTBUY="ubuntu@23.22.167.212"

#SETUP EBAY INSTANCE
ssh -i ../../../Cloud.pem $EBAY 'rm -rf /home/ubuntu/nutch'
ssh -i ../../../Cloud.pem $AMAZON 'rm -rf /home/ubuntu/nutch'
ssh -i ../../../Cloud.pem $WALMART 'rm -rf /home/ubuntu/nutch'
ssh -i ../../../Cloud.pem $BESTBUY 'rm -rf /home/ubuntu/nutch'




